import { Cliente, Produto, ArquivoSTL, Pedido, ItemEstoque, TransacaoFinanceira, Filamento, Impressora } from "./types";

export const MOCK_FILAMENTOS: Filamento[] = [
  { id: "fil-pla-prem", nome: "PLA Premium", marca: "3D Fila", tipo: "PLA", preco: 125.0, peso: 1000, cor: "#10B981" },
  { id: "fil-petg-res", nome: "PETG Resistente", marca: "Esun", tipo: "PETG", preco: 145.0, peso: 1000, cor: "#3B82F6" },
  { id: "fil-abs-sol", nome: "ABS Super Sólido", marca: "Voolt3D", tipo: "ABS", preco: 98.0, peso: 1000, cor: "#F59E0B" },
  { id: "fil-tpu-flex", nome: "TPU Flexível", marca: "GTMax", tipo: "TPU", preco: 190.0, peso: 800, cor: "#8B5CF6" },
  { id: "fil-res-stand", nome: "Resina Standard", marca: "Elegoo", tipo: "Resin", preco: 210.0, peso: 1000, cor: "#EC4899" },
];

export const MOCK_IMPRESSORAS: Impressora[] = [
  { 
    id: "imp-ender", 
    nome: "Creality Ender 3 S1 Pro", 
    marca: "Creality",
    modelo: "Ender 3 S1 Pro",
    volumeX: 220, volumeY: 220, volumeZ: 270,
    potencia: 150, 
    custoDepreciacaoHora: 0.35,
    horasTotais: 1420,
    horasDisponiveis: 24,
    horasDesdeManutencao: 45,
    status: "imprimindo",
    manutencaoLubrificacao: 15, // horas desde a ultima
    manutencaoTrocaBico: 120, // horas desde ultima troca de bico (limite 200)
    manutencaoCorreia: 420,
  },
  { 
    id: "imp-bambu", 
    nome: "Bambu Lab P1S CoreXY", 
    marca: "Bambu Lab",
    modelo: "P1S",
    volumeX: 256, volumeY: 256, volumeZ: 256,
    potencia: 220, 
    custoDepreciacaoHora: 0.85,
    horasTotais: 840,
    horasDisponiveis: 24,
    horasDesdeManutencao: 12,
    status: "disponivel",
    manutencaoLubrificacao: 12,
    manutencaoTrocaBico: 40,
    manutencaoCorreia: 80,
  },
  { 
    id: "imp-bambu-2", 
    nome: "Bambu Lab X1 Carbon", 
    marca: "Bambu Lab",
    modelo: "X1C",
    volumeX: 256, volumeY: 256, volumeZ: 256,
    potencia: 240, 
    custoDepreciacaoHora: 1.20,
    horasTotais: 1950,
    horasDisponiveis: 24,
    horasDesdeManutencao: 98, // Alerta de manutenção em breve!
    status: "manutencao",
    manutencaoLubrificacao: 98, // Passou de 80h -> alerta!
    manutencaoTrocaBico: 198, // Passou de 150h -> bico gasto!
    manutencaoCorreia: 298,
  },
  { 
    id: "imp-resin", 
    nome: "Elegoo Mars 4 DLP", 
    marca: "Elegoo",
    modelo: "Mars 4 Ultra",
    volumeX: 153, volumeY: 77, volumeZ: 175,
    potencia: 65, 
    custoDepreciacaoHora: 0.60,
    horasTotais: 320,
    horasDisponiveis: 18,
    horasDesdeManutencao: 5,
    status: "ociosa",
    manutencaoLubrificacao: 5,
    manutencaoTrocaBico: 5,
    manutencaoCorreia: 5,
  },
];

export const MOCK_CLIENTES: Cliente[] = [
  {
    id: "cli-1",
    nome: "Ana Carolina de Souza",
    telefone: "(11) 98765-4321",
    whatsapp: "5511987654321",
    instagram: "@anacarol_design",
    email: "carolina.souza@design.com",
    cidade: "São Paulo - SP",
    endereco: "Av. Paulista, 1000 - Ap 42",
    origem: "Instagram",
    vip: true,
    observacoes: "Arquiteta de interiores. Sempre compra maquetes de alto padrão e exige acabamento impecável.",
    totalGasto: 4850.00,
    lucroGerado: 3100.00,
    produtosCompradosCount: 12,
  },
  {
    id: "cli-2",
    nome: "Rodrigo Mendes - GeekCorp",
    telefone: "(21) 99888-2233",
    whatsapp: "5521998882233",
    instagram: "@geekcorp_br",
    email: "rodrigo@geekcorp.com.br",
    cidade: "Rio de Janeiro - RJ",
    endereco: "Rua Voluntários da Pátria, 450",
    origem: "Indicação",
    vip: true,
    observacoes: "Lojista de colecionáveis. Encomenda lotes de Action Figures em alta escala. Excelente recorrência.",
    totalGasto: 12400.00,
    lucroGerado: 7800.00,
    produtosCompradosCount: 45,
  },
  {
    id: "cli-3",
    nome: "Marcos Paulo Eng",
    telefone: "(31) 97111-4455",
    whatsapp: "5531971114455",
    instagram: "@mp_engenharia",
    email: "marcos@mpengenharia.com",
    cidade: "Belo Horizonte - MG",
    endereco: "Rua Paraíba, 820",
    origem: "Website",
    vip: false,
    observacoes: "Protótipos funcionais e gabaritos industriais em ABS/PETG. Exige alta precisão dimensional.",
    totalGasto: 2900.00,
    lucroGerado: 1750.00,
    produtosCompradosCount: 5,
  },
  {
    id: "cli-4",
    nome: "Gabriela Rocha (Festa dos Sonhos)",
    telefone: "(19) 98122-7788",
    whatsapp: "5519981227788",
    instagram: "@festas_sonhos_gabi",
    email: "contato@festasdosonhos.com",
    cidade: "Campinas - SP",
    endereco: "Rua das Américas, 122",
    origem: "Instagram",
    vip: false,
    observacoes: "Topo de bolo, brindes e cortadores de biscoito personalizados. Alta rotatividade de itens pequenos.",
    totalGasto: 1550.00,
    lucroGerado: 950.00,
    produtosCompradosCount: 8,
  }
];

export const MOCK_STLS: ArquivoSTL[] = [
  {
    id: "stl-hollow",
    nome: "Hollow Knight Premium Action Figure",
    imagem: "https://images.unsplash.com/photo-1608889175123-8ec330b86f84?q=80&w=200&auto=format&fit=crop",
    arquivoNome: "Hollow_Knight_Action_Figure_v2.stl",
    fornecedor: "Patreon - Craft3D",
    autor: "Ivan_3DDesign",
    licenca: "Comercial (Merchant Tier)",
    categoria: "Colecionáveis",
    tags: ["Geek", "Jogo", "Hollow Knight", "Action Figure"],
    peso: 45,
    tempoMinutos: 310,
    falhas: 1,
    versao: "2.1",
    observacoes: "Necessita suportes orgânicos/árvore na capa. Recomenda-se PLA Premium de alta definição."
  },
  {
    id: "stl-headset",
    nome: "Suporte Headset Articulado",
    imagem: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=200&auto=format&fit=crop",
    arquivoNome: "Modular_Headset_Stand_Universal.stl",
    fornecedor: "Thingiverse",
    autor: "EnderMan99",
    licenca: "CC BY-NC (Uso Comercial Autorizado por Royalty)",
    categoria: "Organizadores",
    tags: ["Setup", "Escritório", "Suporte", "Articulado"],
    peso: 120,
    tempoMinutos: 540,
    falhas: 0,
    versao: "1.4",
    observacoes: "Imprimir com 4 paredes para máxima resistência. Sem necessidade de suportes."
  },
  {
    id: "stl-gear",
    nome: "Engrenagem Helicoidal Industrial - Módulo 2",
    imagem: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=200&auto=format&fit=crop",
    arquivoNome: "Helical_Gear_Mod2_M20.stl",
    fornecedor: "Interno (Desenho Técnico)",
    autor: "Eng. Marcos Paulo",
    licenca: "Privada / Patenteada",
    categoria: "Industrial",
    tags: ["Mecânica", "Protótipo", "Engrenagem", "PETG"],
    peso: 85,
    tempoMinutos: 280,
    falhas: 2,
    versao: "3.0 (Final)",
    observacoes: "Imprimir em PETG ou ABS. Infill de 60% giroidal para excelente resistência torcional."
  },
  {
    id: "stl-vaso",
    nome: "Vaso Espiral Orgânico Moderno",
    imagem: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?q=80&w=200&auto=format&fit=crop",
    arquivoNome: "Organic_Spiral_Vase_Spiralized.stl",
    fornecedor: "Printables",
    autor: "VaseMaker3D",
    licenca: "Comercial Livre",
    categoria: "Decoração",
    tags: ["Modo Vaso", "Decoração", "Minimalista"],
    peso: 35,
    tempoMinutos: 110,
    falhas: 0,
    versao: "1.0",
    observacoes: "Imprimir com 'Modo Vaso' (Spiralize Outer Contour) ativo, bico de 0.6mm ou maior recomendado."
  }
];

export const MOCK_PRODUTOS: Produto[] = [
  {
    id: "prod-hollow",
    nome: "Hollow Knight - Action Figure Pintado",
    imagem: "https://images.unsplash.com/photo-1608889175123-8ec330b86f84?q=80&w=200&auto=format&fit=crop",
    categoria: "Colecionáveis",
    descricao: "Miniatura do icônico Hollow Knight com pintura manual e base decorativa de luxo.",
    stlId: "stl-hollow",
    pesoMedio: 50,
    tempoMedioMinutos: 310,
    quantidade: 4,
    material: "PLA Premium",
    cor: "Cinza Grafite / Pintado",
    infill: 15,
    suportes: "arvore",
    posProcessamento: "pintura",
    precoMinimo: 65.0,
    precoIdeal: 95.0,
    precoPremium: 140.0,
    lucro: 58.0,
    lucroHora: 11.22,
    lucroGrama: 1.16,
    rentabilidade: "boa",
    indiceFalha: 8,
    ativo: true
  },
  {
    id: "prod-headset",
    nome: "Suporte de Headset Articulado Office",
    imagem: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=200&auto=format&fit=crop",
    categoria: "Organizadores",
    descricao: "Suporte articulável ultra resistente para mesa de PC gamer ou escritório profissional.",
    stlId: "stl-headset",
    pesoMedio: 130,
    tempoMedioMinutos: 540,
    quantidade: 15,
    material: "PETG Resistente",
    cor: "Preto Fosco",
    infill: 30,
    suportes: "nenhum",
    posProcessamento: "lixamento",
    precoMinimo: 90.0,
    precoIdeal: 130.0,
    precoPremium: 180.0,
    lucro: 78.50,
    lucroHora: 8.72,
    lucroGrama: 0.60,
    rentabilidade: "aceitavel",
    indiceFalha: 3,
    ativo: true
  },
  {
    id: "prod-engrenagem",
    nome: "Gabarito Helicoidal de Redução",
    imagem: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=200&auto=format&fit=crop",
    categoria: "Industrial",
    descricao: "Engrenagem helicoidal customizada para maquinário leve. Alta precisão e dureza mecânica.",
    stlId: "stl-gear",
    pesoMedio: 85,
    tempoMedioMinutos: 280,
    quantidade: 2,
    material: "ABS Sólido",
    cor: "Laranja Segurança",
    infill: 60,
    suportes: "normal",
    posProcessamento: "nenhum",
    precoMinimo: 110.0,
    precoIdeal: 160.0,
    precoPremium: 220.0,
    lucro: 112.0,
    lucroHora: 24.0, // Excelente rentabilidade por hora!
    lucroGrama: 1.31,
    rentabilidade: "excelente",
    indiceFalha: 15, // Risco alto de empenamento
    ativo: true
  },
  {
    id: "prod-vaso",
    nome: "Vaso Orgânico Minimalista Deco",
    imagem: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?q=80&w=200&auto=format&fit=crop",
    categoria: "Decoração",
    descricao: "Vaso decorativo orgânico texturizado impresso em modo espiral contínuo com acabamento brilhante.",
    stlId: "stl-vaso",
    pesoMedio: 35,
    tempoMedioMinutos: 110,
    quantidade: 8,
    material: "PLA Seda",
    cor: "Champagne Ouro",
    infill: 0,
    suportes: "nenhum",
    posProcessamento: "nenhum",
    precoMinimo: 35.0,
    precoIdeal: 55.0,
    precoPremium: 75.0,
    lucro: 42.0,
    lucroHora: 22.90, // Fabuloso lucro por hora devido ao curto tempo
    lucroGrama: 1.20,
    rentabilidade: "excelente",
    indiceFalha: 1,
    ativo: true
  }
];

export const MOCK_PEDIDOS: Pedido[] = [
  {
    id: "PED-1001",
    titulo: "3x Hollow Knight Deluxe",
    clienteId: "cli-2",
    clienteNome: "Rodrigo Mendes - GeekCorp",
    data: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    status: "imprimindo",
    tempoPrevistoMinutos: 930,
    tempoRealMinutos: 620,
    falhasCount: 1,
    observacoes: "Imprimindo na Bambu Lab. Exige pintura detalhada na sequência.",
    operador: "Daniel S.",
    impressoraId: "imp-ender",
    totalPago: 285.00,
    lucroLiquido: 174.00,
    pesoG: 150
  },
  {
    id: "PED-1002",
    titulo: "Protótipos Engrenagem Helicoidal",
    clienteId: "cli-3",
    clienteNome: "Marcos Paulo Eng",
    data: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    status: "fila",
    tempoPrevistoMinutos: 560,
    tempoRealMinutos: 0,
    falhasCount: 0,
    observacoes: "Material ABS Laranja. Aplicar suco de ABS na mesa antes de iniciar para evitar warping.",
    operador: "Daniel S.",
    impressoraId: "imp-bambu",
    totalPago: 320.00,
    lucroLiquido: 224.00,
    pesoG: 170
  },
  {
    id: "PED-1003",
    titulo: "Suporte Headset Articulado",
    clienteId: "cli-1",
    clienteNome: "Ana Carolina de Souza",
    data: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    status: "pos-processamento",
    tempoPrevistoMinutos: 540,
    tempoRealMinutos: 555,
    falhasCount: 0,
    observacoes: "Fazer lixamento suave nas juntas rotativas para garantir movimento perfeito.",
    operador: "Carla M.",
    impressoraId: "imp-bambu-2",
    totalPago: 130.00,
    lucroLiquido: 78.50,
    pesoG: 130
  },
  {
    id: "PED-1004",
    titulo: "Lote de 5 Vasos Champanhe",
    clienteId: "cli-4",
    clienteNome: "Gabriela Rocha (Festa dos Sonhos)",
    data: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    status: "entregue",
    tempoPrevistoMinutos: 550,
    tempoRealMinutos: 530,
    falhasCount: 0,
    observacoes: "Modo vaso ativo. Cliente adorou o acabamento brilhoso champanhe.",
    operador: "Daniel S.",
    impressoraId: "imp-bambu",
    totalPago: 275.00,
    lucroLiquido: 210.00,
    pesoG: 175
  },
  {
    id: "PED-1005",
    titulo: "Maquete Residencial Escopo A",
    clienteId: "cli-1",
    clienteNome: "Ana Carolina de Souza",
    data: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    status: "pagamento",
    tempoPrevistoMinutos: 1800,
    tempoRealMinutos: 0,
    falhasCount: 0,
    observacoes: "Aguardando confirmação de PIX de 50% de sinal para dar play.",
    operador: "Carla M.",
    impressoraId: "imp-bambu-2",
    totalPago: 1100.00,
    lucroLiquido: 720.00,
    pesoG: 450
  },
  {
    id: "PED-1006",
    titulo: "Cortadores de Biscoito Personalizados",
    clienteId: "cli-4",
    clienteNome: "Gabriela Rocha (Festa dos Sonhos)",
    data: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    status: "entregue",
    tempoPrevistoMinutos: 180,
    tempoRealMinutos: 195,
    falhasCount: 1,
    observacoes: "Filamento PLA Grau Alimentício. Impressão rápida bico 0.4.",
    operador: "Daniel S.",
    impressoraId: "imp-ender",
    totalPago: 120.00,
    lucroLiquido: 85.00,
    pesoG: 60
  },
  {
    id: "PED-1007",
    titulo: "Busto Yoda Realista Resina",
    clienteId: "cli-2",
    clienteNome: "Rodrigo Mendes - GeekCorp",
    data: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    status: "embalando",
    tempoPrevistoMinutos: 360,
    tempoRealMinutos: 380,
    falhasCount: 0,
    observacoes: "Cura UV finalizada. Envolver em bastante plástico bolha pois os detalhes das orelhas são frágeis.",
    operador: "Carla M.",
    impressoraId: "imp-resin",
    totalPago: 240.00,
    lucroLiquido: 145.00,
    pesoG: 90
  }
];

export const MOCK_ESTOQUE: ItemEstoque[] = [
  { id: "est-1", categoria: "filamentos", nome: "Filamento PLA Premium Verde Jade", fornecedor: "3D Fila", valor: 125.00, lote: "PLA-VJ-2026", quantidade: 4, pesoRestanteG: 3200, estoqueMinimo: 2, corHex: "#10B981" },
  { id: "est-2", categoria: "filamentos", nome: "Filamento PETG Azul Cósmico", fornecedor: "Esun", valor: 145.00, lote: "PETG-AC-99", quantidade: 5, pesoRestanteG: 4800, estoqueMinimo: 2, corHex: "#3B82F6" },
  { id: "est-3", categoria: "filamentos", nome: "Filamento ABS Laranja Alerta", fornecedor: "Voolt3D", valor: 98.00, lote: "ABS-LA-3", quantidade: 1, pesoRestanteG: 450, estoqueMinimo: 2, corHex: "#F59E0B" }, // ALERTA ESTOQUE BAIXO!
  { id: "est-4", categoria: "resinas", nome: "Resina Standard Cinza Opaca 4K", fornecedor: "Elegoo", valor: 210.00, lote: "RES-CO-4K", quantidade: 3, pesoRestanteG: 2200, estoqueMinimo: 1, corHex: "#EC4899" },
  { id: "est-5", categoria: "parafusos", nome: "Parafuso M3 Allen Cabeça Cilíndrica (100 unidades)", fornecedor: "ParafusoCenter", valor: 18.50, lote: "M3-ALL-10", quantidade: 12, estoqueMinimo: 5 },
  { id: "est-6", categoria: "imas", nome: "Ímã Neodímio NdFeB N35 5x2mm (50 unidades)", fornecedor: "SuperIma", valor: 29.90, lote: "IMA-N52", quantidade: 8, estoqueMinimo: 3 },
  { id: "est-7", categoria: "embalagens", nome: "Caixa de Papelão Reforçada 20x20x20cm (25 unidades)", fornecedor: "EmbalaMais", valor: 55.00, lote: "CX-20-A", quantidade: 2, estoqueMinimo: 4 } // ALERTA ESTOQUE BAIXO!
];

export const MOCK_FINANCEIRO: TransacaoFinanceira[] = [
  { id: "tx-1", tipo: "receita", categoria: "Venda", valor: 1100.00, metodo: "pix", data: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(), descricao: "Sinal maquete residencial - Ana Carolina" },
  { id: "tx-2", tipo: "receita", categoria: "Venda", valor: 275.00, metodo: "pix", data: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(), descricao: "Pedido lote de vasos champanhe - Gabi" },
  { id: "tx-3", tipo: "despesa", categoria: "Compra Filamento", valor: 250.00, metodo: "cartao", data: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(), descricao: "Compra de 2 rolos de PLA Premium - 3D Fila" },
  { id: "tx-4", tipo: "despesa", categoria: "Manutenção", valor: 45.00, metodo: "pix", data: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(), descricao: "Troca de bico de latão e lubrificante de correia" },
  { id: "tx-5", tipo: "receita", categoria: "Venda", valor: 450.00, metodo: "pix", data: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(), descricao: "Sinal GeekCorp Lote Action Figures" },
  { id: "tx-6", tipo: "despesa", categoria: "Energia", valor: 184.20, metodo: "pix", data: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(), descricao: "Fatura de luz proporcional da farm de impressoras" },
  { id: "tx-7", tipo: "receita", categoria: "Venda", valor: 320.00, metodo: "cartao", data: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(), descricao: "Gabarito mecânico - Marcos Paulo Eng" }
];
